title: Sheng-Liang Song
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Sheng-Liang Song"
job: "〈Senior Software Engineer〉"

phone_number: 510-766-xxxx
address: Fremont, California
email: shengliang.song@gmail.com
linkedin_username: shenglia
github_username: shengliang
blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
